# volumes:
#   config:
#     driver_opts:
#       o : volume
#       type : none
#       device: /home/lescribe/Documents/Depot/inception/srcs/nginx/test/
        #   type : volume
        #   source : ./nginx/test
        #   target : /etc/nginx/http.d/
    #   name: config
    #   driver_opts:
    #     device: ./nginx/test/
    # website:
    #   driver_opts:
    #     device: ./nginx/site/

networks:
  frontend:
  backend:

services:
  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    ports:
      - "443:443"
    networks:
      - frontend
    depends_on:
      - wordpress
    restart: on-failure
    volumes:
      - /home/data/wordpress:/var/www/wordpress
        #    - ./nginx/config:/etc/nginx/http.d/
        #    - ./nginx/website:/var/www/localhost/

  wordpress:
    container_name: wordpress
    image: wordpress:6.1.0-php8.0-fpm-alpine
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /home/data/wordpress:/var/www/wordpress
        #   environment:
        #     - WP_PATH=${WP_PATH}
        #     - DB_HOST=${DB_HOST}
        #     - DB_NAME=${DB_NAME}
        #     - DB_USERNAME=${DB_USERNAME}
        #     - DB_PASSWORD=${DB_PASSWORD}
        #     - DB_ADMIN=${DB_ADMIN}
        #     - DB_ADMIN_PASS=${DB_ADMIN_PASS}

  mariadb:
    image: mariadb:10.10.1-rc-jammy
    container_name: mariadb
    ports:
      - "3306"
    networks:
      - backend
    env_file:
      - .env
    restart: on-failure
        #environment:
        #  - DB_NAME=${DB_NAME}
        #  - DB_USERNAME=${DB_USERNAME}
        #  - DB_PASSWORD=${DB_PASSWORD}
        #  - DB_ADMIN=${DB_ADMIN}
        #  - DB_ADMIN_PASS=${DB_ADMIN_PASS}
