networks:
  frontend:
  backend:

services:
  nginx:
    build:
      context: ./requirement/Nginx/
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - frontend
    restart: on-failure
    volumes:
      - website:/var/www/wordpress/
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirement/Wordpress
      args:
        - WP_PATH=${WP_PATH}
        - WORDPRESS_DB_HOST=${MARIADB_HOST}
        - WORDPRESS_DB_USER=${MARIADB_USER}
        - WORDPRESS_DB_PASS=${MARIADB_PASSWORD}
        - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
        - WORDPRESS_REDIS_HOST=${REDIS_HOST}
        - WORDPRESS_TABLE_PREFIX=${TABLE_PREFIX}
    container_name: wordpress
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: on-failure
    volumes:
      - website:/var/www/wordpress/

  mariadb:
    env_file: .env
    build:
      context: ./requirement/Mariadb
      args: 
        - DB_NAME=${MARIADB_DATABASE}
        - DB_ADMIN=${MARIADB_USER}
        - DB_ADMIN_PASS=${MARIADB_PASSWORD}
        - MARIADB_ROOT_PASS=${MARIADB_ROOT_PASS}
    volumes:
      - database:/var/lib/mysql/
        #      - /home/iguidado/data/db:/var/lib/mysql/
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - backend
    restart: on-failure

  adminer:
    build:
      context: requirement/Bonus/Adminer/
    container_name: adminer
    depends_on:
      - wordpress
    restart: on-failure
    expose:
      - "9000"
    networks:
      - frontend
      - backend
    volumes:
      - website:/var/www/wordpress/
        # - /home/iguidado/data/wordpress:/var/www/wordpress/

  redis:
    build:
      context: requirement/Bonus/Redis/
    container_name: redis
    restart: on-failure
    expose:
      - "6379"
    networks:
      - backend

        # ftp:
        #   build:
        #     context: requirement/Bonus/Ftp/
        #   container_name: ftp
        #   restart: on-failure
        #   ports:
        #     - "0.0.0.0:20:20"
        #     - "0.0.0.0:21:21"
        #   networks:
        #     - backend
        #   volumes:
        #     - /home/iguidado/data/wordpress:/var/lib/ftp/

volumes:
  website:
    driver_opts:
      o : bind
      type : none
      device: /home/iguidado/data/wordpress
  database:
    driver_opts:
      o : bind
      type : none
      device: /home/iguidado/data/db
