networks:
  frontend:
  backend:

services:
        #        adminer:
        #          image: adminer
        #          container_name: adminer
        #       
  nginx:
    build:
      context: ./requirement/Nginx/
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - frontend
    restart: on-failure
    volumes:
      - ~/data/:/var/www/
    depends_on:
      - wordpress
 
  wordpress:
    #   environment:
    #     - WP_PATH=${WP_PATH}
    #     - WORDPRESS_DB_HOST=${MARIADB_HOST}
    #     - WORDPRESS_DB_USER=${MARIADB_USER}
    #     - WORDPRESS_DB_PASS=${MARIADB_PASSWORD}
    #     - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
    #     - WORDPRESS_TABLE_PREFIX=${TABLE_PREFIX}
    build:
      context: ./requirement/Wordpress
      args:
        - WP_PATH=${WP_PATH}
        - WORDPRESS_DB_HOST=${MARIADB_HOST}
        - WORDPRESS_DB_USER=${MARIADB_USER}
        - WORDPRESS_DB_PASS=${MARIADB_PASSWORD}
        - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
        - WORDPRESS_REDIS_HOST=${WP_REDIS_HOST}
        - WORDPRESS_TABLE_PREFIX=${TABLE_PREFIX}
    container_name: wordpress
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: on-failure
    volumes:
      - ~/data/wordpress:/var/www/wordpress/

  mariadb:
    env_file: .env
    build:
      context: ./requirement/Mariadb
      args: 
        - DB_NAME=${MARIADB_DATABASE}
        - DB_ADMIN=${MARIADB_USER}
        - DB_ADMIN_PASS=${MARIADB_PASSWORD}
        - MARIADB_ROOT_PASS=${MARIADB_ROOT_PASS}
    volumes:
      - /home/iguidado/data/db:/var/lib/mysql/
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - backend
    restart: on-failure

      # volumes:
      #   config:
      #     driver_opts:
      #       o : volume
      #       type : none
      #       device: /home/lescribe/Documents/Depot/inception/srcs/nginx/test/
      #   type : volume
      #   source : ./nginx/test
      #   target : /etc/nginx/http.d/
      #   name: config
      #   driver_opts:
      #     device: ./nginx/test/
      # website:
      #   driver_opts:
      #     device: ./nginx/site/
