networks:
  frontend:
  backend:

services:
  nginx:
    build:
      context: ./requirement/Nginx/
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - frontend
    depends_on:
      - wordpress
    restart: on-failure
    volumes:
      - ${HOME}/data/wordpress:/var/www/wordpress/
      #      - ./nginx/config:/etc/nginx/http.d/
  
  wordpress:
    build:
      context: ./requirement/Wordpress
      args:
        - WP_PATH=${WP_PATH}
        - WORDPRESS_DB_HOST=${MARIADB_HOST}
        - WORDPRESS_DB_USER=${MARIADB_USER}
        - WORDPRESS_DB_PASS=${MARIADB_PASSWORD}
        - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
        - WORDPRESS_TABLE_PREFIX=${TABLE_PREFIX}
    container_name: wordpress
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: on-failure
    volumes:
      - ${HOME}/data/wordpress:/var/www/wordpress/

  mariadb:
    env_file: .env
    build:
      context: ./requirement/Mariadb
      args: 
        - MARIADB_NAME=${MARIADB_DATABASE}
        - MARIADB_USERNAME=${MARIADB_USER}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    container_name: mariadb
    ports:
      - "3306"
    networks:
      - backend
    restart: on-failure
      #environment:
      #  - DB_NAME=${DB_NAME}
      #  - DB_USERNAME=${DB_USERNAME}
      #  - DB_PASSWORD=${DB_PASSWORD}
      #  - DB_ADMIN=${DB_ADMIN}
      #  - DB_ADMIN_PASS=${DB_ADMIN_PASS}

      # volumes:
      #   config:
      #     driver_opts:
      #       o : volume
      #       type : none
      #       device: /home/lescribe/Documents/Depot/inception/srcs/nginx/test/
      #   type : volume
      #   source : ./nginx/test
      #   target : /etc/nginx/http.d/
      #   name: config
      #   driver_opts:
      #     device: ./nginx/test/
      # website:
      #   driver_opts:
      #     device: ./nginx/site/

