services:
  # nginx:
  #   image: "nginx:alpine"
  #     #ports:
  #     #     - "80:80"
  #     #     - "443:443"
  #       #   volumes:
  #       #     - "./volumes/conf.d:/etc/nginx/conf.d/"
  #   container_name: "nginx"
  #   restart: on-failure
  wordpress:
    image: "wordpress:6.0.2-fpm-alpine"
    container_name: "wordpress"
    ports:
      - "80:80"
      - "9000"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    restart: on-failure
      # mariadb:
      #   images: mariadb:latest
      #   container_name: mariadb
      # wordpress:
      #   images: wordpress:latest
      #   container_name: wordpress
