CREATE DATABASE DB_NAME;
CREATE USER 'USERNAME'@'WP_HOST' IDENTIFIED BY 'DB_PASS';
CREATE USER 'DB_ADMIN'@'WP_HOST' IDENTIFIED BY 'DB_ADMIN_PASS';
GRANT ALL PRIVILEGES ON DB_NAME TO 'DB_ADMIN'@'WP_HOST';
FLUSH PRIVILEGES;
quit
