CREATE DATABASE DB_NAME;

CREATE USER 'DB_ADMIN'@'%' IDENTIFIED BY 'DB_ADMIN_PASS';
GRANT ALL PRIVILEGES ON DB_NAME.* TO 'DB_ADMIN'@'%';

DELETE FROM mysql.user WHERE User='';

FLUSH PRIVILEGES;
quit
