CREATE DATABASE DB_NAME;
CREATE USER 'USERNAME'@'%' IDENTIFIED BY 'DB_PASS';
CREATE USER 'DB_ADMIN'@'%' IDENTIFIED BY 'DB_ADMIN_PASS';
GRANT ALL PRIVILEGES ON DB_NAME TO 'DB_ADMIN'@'%';
FLUSH PRIVILEGES;
quit
