on:
  push:
    branches: [main, ci]
  workflow_dispatch:
jobs:
  test_stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: create .env file
        run: make env-ci
      - name: check docker-compose file
        run: docker compose -f srcs/docker-compose.yml config -q
      - name: build docker images
        run: make build-ci
      - name: run container
        run: make up-ci
      - name: wait for stacks to up
        run: make wait-ci
      - name: test nginx
        run: curl -k https://localhost
      - name: test wordpress
        run: curl -k https://localhost/wp-login.php
#     - name: scan vulnerabilities
      - name: Clean up Docker resources
        run: make prune